### ISSUE TITLE
Devbox shell fails on arch linux

### ISSUE THREAD

**Issue by asp143** [jetify-com/devbox#2291] opened 2024-09-23 09:02 UTC
### What happened?

When running `devbox shell` command says invalid URL

### Steps to reproduce

1. devbox init
2. devbox add go
3. devbox shell

### Command

`devbox shell`

### devbox.json

```jsonc
{
  "$schema":  "https://raw.githubusercontent.com/jetify-com/devbox/0.13.0/.schema/devbox.schema.json",
  "packages": ["go"],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

### Devbox version

0.13.0

### Nix version

N/A 

### What system does this bug occur on?

Linux (x86-64)

### Debug logs

Error: nix: command error: nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' print-dev-env --json 'path:/home/ralph/Documents/Syncthing/Projects/Side Projects/Work/rff/test/concurency/.devbox/gen/flake': 'path:/home/ralph/Documents/Syncthing/Projects/Side Projects/Work/rff/test/concurency/.devbox/gen/flake' is not a valid URL: exit code 1

time=2024-09-23T16:58:18.960+08:00 level=ERROR source=go.jetpack.io/devbox/internal/boxcli/midcobra/debug.go:68 msg="command error" stderr="error: 'path:/home/ralph/Documents/Syncthing/Projects/Side Projects/Work/rff/test/concurency/.devbox/gen/flake' is not a valid URL\n" execid=25e2e4b9e4a745eb87bff662d511dcc1 stack=<nil>
time=2024-09-23T16:58:18.960+08:00 level=ERROR source=go.jetpack.io/devbox/internal/boxcli/midcobra/debug.go:70 msg="command error" execid=25e2e4b9e4a745eb87bff662d511dcc1 stack=<nil>
time=2024-09-23T16:58:18.960+08:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-09-23T16:58:18.960+08:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-09-23T16:58:18.960+08:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path="/home/ralph/Documents/Syncthing/Projects/Side Projects/Work/rff/test/concurency/devbox.json" dur=181.46µs
time=2024-09-23T16:58:18.960+08:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:202 msg="package doesn't need patching" pkg=go mode=auto

**Comment by asp143** [comment] 2024-09-23 09:14
I tested this whitespace issue I found, it  seems the whitespace is the issue. Is there a way to fix this without changing the name of the folder?

https://github.com/jetify-com/devbox/issues/2290

**Comment by gcurtis** [comment] 2024-09-23 14:05
@asp143 I'm going to close this as a duplicate of #2290. We'll try to get this fixed today.

**Closed by gcurtis** 2024-09-23 14:05 UTC
Labels: bug, triage

**Comment by asp143** [comment] 2024-09-23 14:45
thanks @gcurtis!
